/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelCliente;

/**
 *
 * @author Advan
 */
public class ViewCliente extends javax.swing.JFrame {

    
    ViewEndereco viewEndereco = new ViewEndereco();
    ModelCliente modelCliente = new ModelCliente();
    ControllerCliente controllerCliente = new ControllerCliente();
    List<ModelCliente> listaCliente = new ArrayList();
    String AltCadas = "Cadastrar";
    
    /**
     * Creates new form ViewCliente
     */
    public ViewCliente() {
        initComponents();
        setLocationRelativeTo(null);
        carregarListaCliente();
        carregaCodigo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel1 = new javax.swing.JPanel();
        View_Cli_Bt_Salvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        View_Cli_Nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        View_ComboBox_M_F = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        View_Cli_RSocial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        View_Cli_InscEstadual = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        View_Cli_NFantasia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        View_Cli_DataCadastro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        View_Cli_Tabela = new javax.swing.JTable();
        View_Cli_Bt_Limpar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        View_Cli_Email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        View_Cli_Id = new javax.swing.JTextField();
        View_Cli_Bt_Alterar = new javax.swing.JButton();
        View_Cli_Bt_Excluir = new javax.swing.JButton();
        View_ComboBox_PJ_PF = new javax.swing.JComboBox<>();
        btn_voltar_cli = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        View_Con_Capital = new javax.swing.JFormattedTextField();
        View_Cli_CPF = new javax.swing.JFormattedTextField();
        View_Cli_Tel = new javax.swing.JFormattedTextField();
        View_Cli_CNPJ = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        View_Cli_Bt_Salvar.setText("Cadastrar");
        View_Cli_Bt_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_Cli_Bt_SalvarActionPerformed(evt);
            }
        });

        jLabel2.setText("Classe");

        jLabel1.setText("Nome");

        jLabel4.setText("CPF");

        View_ComboBox_M_F.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Feminino", "Masculino" }));

        jLabel3.setText("Sexo");

        jLabel5.setText("CNPJ");

        jLabel6.setText("Razão Social");

        jLabel7.setText("Inscrição Estadual");

        jLabel8.setText("Nome Fantasia");

        jLabel9.setText("Data Cadastro");

        View_Cli_DataCadastro.setEditable(false);

        View_Cli_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome/Razão", "CPF/CNPJ", "Telefone", "E-mail", "Status", "Data Criação", "Classe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(View_Cli_Tabela);
        if (View_Cli_Tabela.getColumnModel().getColumnCount() > 0) {
            View_Cli_Tabela.getColumnModel().getColumn(0).setMinWidth(80);
            View_Cli_Tabela.getColumnModel().getColumn(0).setPreferredWidth(80);
            View_Cli_Tabela.getColumnModel().getColumn(0).setMaxWidth(80);
            View_Cli_Tabela.getColumnModel().getColumn(5).setMinWidth(80);
            View_Cli_Tabela.getColumnModel().getColumn(5).setPreferredWidth(80);
            View_Cli_Tabela.getColumnModel().getColumn(5).setMaxWidth(80);
            View_Cli_Tabela.getColumnModel().getColumn(6).setMinWidth(80);
            View_Cli_Tabela.getColumnModel().getColumn(6).setPreferredWidth(80);
            View_Cli_Tabela.getColumnModel().getColumn(6).setMaxWidth(80);
            View_Cli_Tabela.getColumnModel().getColumn(7).setMinWidth(1);
            View_Cli_Tabela.getColumnModel().getColumn(7).setPreferredWidth(1);
            View_Cli_Tabela.getColumnModel().getColumn(7).setMaxWidth(1);
        }

        View_Cli_Bt_Limpar.setText("Limpar");
        View_Cli_Bt_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_Cli_Bt_LimparActionPerformed(evt);
            }
        });

        jLabel10.setText("Telefone");

        jLabel11.setText("E-mail");

        jLabel12.setText("Codigo");

        View_Cli_Id.setEditable(false);

        View_Cli_Bt_Alterar.setText("Alterar");
        View_Cli_Bt_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_Cli_Bt_AlterarActionPerformed(evt);
            }
        });

        View_Cli_Bt_Excluir.setText("Excluir");
        View_Cli_Bt_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_Cli_Bt_ExcluirActionPerformed(evt);
            }
        });

        View_ComboBox_PJ_PF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "PF", "PJ" }));
        View_ComboBox_PJ_PF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_ComboBox_PJ_PFActionPerformed(evt);
            }
        });

        btn_voltar_cli.setText("Voltar");
        btn_voltar_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_cliActionPerformed(evt);
            }
        });

        jLabel13.setText("Capital");

        View_Con_Capital.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        View_Con_Capital.setText("R$");

        try {
            View_Cli_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            View_Cli_Tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            View_Cli_CNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout Painel1Layout = new javax.swing.GroupLayout(Painel1);
        Painel1.setLayout(Painel1Layout);
        Painel1Layout.setHorizontalGroup(
            Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addComponent(View_Cli_Bt_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(View_Cli_Bt_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(View_Cli_Bt_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(View_Cli_Bt_Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(View_Cli_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(View_Cli_RSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(View_Cli_InscEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel8)
                                .addGap(0, 88, Short.MAX_VALUE))
                            .addGroup(Painel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(View_Cli_NFantasia))))
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(View_Cli_Nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(View_Cli_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(View_ComboBox_M_F, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(View_Cli_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(View_Cli_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(View_Cli_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(View_ComboBox_PJ_PF, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(View_Con_Capital, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(View_Cli_DataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_voltar_cli)))
                .addContainerGap())
        );
        Painel1Layout.setVerticalGroup(
            Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(View_Cli_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_Cli_DataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_ComboBox_PJ_PF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_Con_Capital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(Painel1Layout.createSequentialGroup()
                            .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1))
                            .addGap(7, 7, 7)
                            .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(View_Cli_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(View_Cli_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(Painel1Layout.createSequentialGroup()
                            .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel10))
                            .addGap(7, 7, 7)
                            .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(View_ComboBox_M_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(View_Cli_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(View_Cli_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(View_Cli_RSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_Cli_InscEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_Cli_NFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_Cli_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(View_Cli_Bt_Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View_Cli_Bt_Alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View_Cli_Bt_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View_Cli_Bt_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_voltar_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void View_Cli_Bt_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_Cli_Bt_SalvarActionPerformed
        // TODO add your handling code here:
        modelCliente = new ModelCliente();
        modelCliente.setId(Integer.parseInt(View_Cli_Id.getText()));
        modelCliente.setNome(View_Cli_Nome.getText());
        modelCliente.setCpf(View_Cli_CPF.getText().replace(" ", "").replace(".", "").replace("-", ""));
        modelCliente.setCnpj(View_Cli_CNPJ.getText().replace(" ", "").replace(".", "").replace("-", "").replace("/", ""));
        modelCliente.setSexo(View_ComboBox_M_F.getSelectedItem().toString());
        modelCliente.setInscricao_estadual(View_Cli_InscEstadual.getText());
        modelCliente.setRazao_social(View_Cli_RSocial.getText());
        modelCliente.setNome_fantasia(View_Cli_NFantasia.getText());
        modelCliente.setTelefone(View_Cli_Tel.getText().replace(" ", "").replace("(", "").replace(") ", "").replace("-", ""));
        modelCliente.setEmail(View_Cli_Email.getText());
        modelCliente.setclasse_cli(View_ComboBox_PJ_PF.getSelectedItem().toString());
        modelCliente.setCapital(Float.parseFloat(View_Con_Capital.getText().replace("R$", "").replace(".", "").replace(",", ".")));
      
        
        if(AltCadas.equals("Cadastrar")){
            
            if(View_ComboBox_PJ_PF.getSelectedItem().toString() == "-"){
                 JOptionPane.showMessageDialog(this, "Erro os Campos Classe deve ser Preenchidos", "Erro", JOptionPane.ERROR_MESSAGE);
            }else{
                 if(controllerCliente.salvarUsuarioController(modelCliente)){
                //cadastrou
                    JOptionPane.showMessageDialog(this, "Cadastro Realizado com Sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    //limpar
                    limparFormulario();
                    carregarListaCliente();
                    carregaCodigo();
                    if(!View_Cli_Id.getText().isEmpty()){
                        
                        viewEndereco.enviaidcliente(modelCliente.getId());
                        viewEndereco.setLocationRelativeTo(null);
                        viewEndereco.setVisible(true);
                        viewEndereco.setResizable(false);
                        setVisible(false);
                    }
                    
                }else{
                //não cadastrou
                    JOptionPane.showMessageDialog(this, "Erro ao Cadastrar", "Erro", JOptionPane.ERROR_MESSAGE);
                }


            }
        }else{
            if(View_ComboBox_PJ_PF.getSelectedItem().toString() == "-"){
             JOptionPane.showMessageDialog(this, "Erro o Campo Classe deve ser Preenchidos", "Erro", JOptionPane.ERROR_MESSAGE);
            }else{
                 if(controllerCliente.atualizarUsuarioController(modelCliente)){
                  //Alterar
                        JOptionPane.showMessageDialog(this, "Cliente Atualizado com Sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                        //limpar
                        limparFormulario();
                        carregarListaCliente();
                        carregaCodigo();
                    }else{
                    //não cadastrou
                        JOptionPane.showMessageDialog(this, "Erro ao Atualizar", "Erro", JOptionPane.ERROR_MESSAGE);
                    }


                }
        }

    }//GEN-LAST:event_View_Cli_Bt_SalvarActionPerformed

    /**
     * Limpa Formulario do cliente
     * 
     */
    private void limparFormulario(){
       
        
        View_Cli_Nome.setText("");
        View_Cli_CPF.setText("");
        View_Cli_CNPJ.setText("");
        View_ComboBox_M_F.setSelectedItem("");
        View_Cli_InscEstadual.setText("");
        View_ComboBox_PJ_PF.setSelectedItem("");
        View_Cli_RSocial.setText("");
        View_Cli_NFantasia.setText("");
        View_Cli_Tel.setText("");
        View_Cli_Email.setText("");
        View_ComboBox_PJ_PF.setSelectedItem("-");
        View_Con_Capital.setText("");
        
        AltCadas = "Cadastrar";
       
    }
    
    
    /**
     * quando selecionar cliente Pf ou Pj so os campos referente a pf e pj estaram disponiveis
     */
    private void regraCampoClasseCli(){
    
        if(View_ComboBox_PJ_PF.getSelectedItem().toString() == "PF"){
             
             View_Cli_CNPJ.setText("");
             View_Cli_CNPJ.setEnabled(false);
             
             View_Cli_RSocial.setText("");
             View_Cli_RSocial.setEnabled(false);
             
             View_Cli_InscEstadual.setText("");
             View_Cli_InscEstadual.setEnabled(false);
             
             View_Cli_NFantasia.setText("");
             View_Cli_NFantasia.setEnabled(false);
             
              View_Cli_CPF.setEnabled(true);
             View_ComboBox_M_F.setEnabled(true);
         }else if(View_ComboBox_PJ_PF.getSelectedItem().toString() == "PJ"){
             View_Cli_CPF.setText("");
             View_Cli_CPF.setEnabled(false);
             View_ComboBox_M_F.setSelectedItem("");
             View_ComboBox_M_F.setEnabled(false);
             
             
             View_Cli_CNPJ.setEnabled(true);
             View_Cli_RSocial.setEnabled(true);
             View_Cli_InscEstadual.setEnabled(true);
             View_Cli_NFantasia.setEnabled(true);
         
         }else if(View_ComboBox_PJ_PF.getSelectedItem().toString() == "-"){
             View_Cli_CNPJ.setEnabled(true);
             View_Cli_RSocial.setEnabled(true);
             View_Cli_InscEstadual.setEnabled(true);
             View_Cli_NFantasia.setEnabled(true);
             View_Cli_CPF.setEnabled(true);
             View_ComboBox_M_F.setEnabled(true);
         }
    }
    
    
    private void carregaCodigo(){
       int recebe = controllerCliente.carregaCodigoController(0);
      Date dt = new Date();
      SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        View_Cli_Id.setText(Integer.toString(recebe));
        View_Cli_DataCadastro.setText(formato.format(dt));
    
    }
    
    /**
     * Carregar Lista na tabela da view Cliente
     *  
     */
    private void carregarListaCliente(){
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        listaCliente = controllerCliente.getListaClienteController();
        DefaultTableModel modelo = (DefaultTableModel) View_Cli_Tabela.getModel();
        modelo.setNumRows(0);
        
        for(int i = 0; i < listaCliente.size(); i++){
            if(listaCliente.get(i).getClasse_cli().equals("PF")){
                modelo.addRow(new Object[]{
                listaCliente.get(i).getId(),
                listaCliente.get(i).getNome(),
                listaCliente.get(i).getCpf(),
                listaCliente.get(i).getTelefone(),
                listaCliente.get(i).getEmail(),
                listaCliente.get(i).getStatus_cli(),
                formato.format(listaCliente.get(i).getData_cadastro())
            });
            }else{
                modelo.addRow(new Object[]{
                listaCliente.get(i).getId(),
                listaCliente.get(i).getRazao_social(),
                listaCliente.get(i).getCnpj(),
                listaCliente.get(i).getTelefone(),
                listaCliente.get(i).getEmail(),
                listaCliente.get(i).getStatus_cli(),
                formato.format(listaCliente.get(i).getData_cadastro())
            });
            }
            
        }
    }
    
   
    
    
    private void View_Cli_Bt_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_Cli_Bt_LimparActionPerformed
        // TODO add your handling code here:
        limparFormulario();
    }//GEN-LAST:event_View_Cli_Bt_LimparActionPerformed

    private void View_Cli_Bt_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_Cli_Bt_ExcluirActionPerformed
        // TODO add your handling code here:
        int linha = View_Cli_Tabela.getSelectedRow();
        if(linha < 0){
            JOptionPane.showMessageDialog(this, "Cliente não selecionado", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }else{
            int codigo = (int) View_Cli_Tabela.getValueAt(linha, 0);
            if(controllerCliente.excluirClienteController(codigo)){
                carregarListaCliente();
                limparFormulario();
                JOptionPane.showMessageDialog(this, "Usuário Excluído", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(this, "Erro ao Excluir", "Erro", JOptionPane.ERROR);   
            }
            
            
        }
    }//GEN-LAST:event_View_Cli_Bt_ExcluirActionPerformed

    private void View_Cli_Bt_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_Cli_Bt_AlterarActionPerformed
        // TODO add your handling code here:
        AltCadas = "Alterar";
        modelCliente = new ModelCliente();
        int linha = View_Cli_Tabela.getSelectedRow();
        if(linha < 0){
            JOptionPane.showMessageDialog(this, "Cliente não selecionado", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }else{
            int idCliente = (int) View_Cli_Tabela.getValueAt(linha, 0);
            modelCliente = controllerCliente.getClienteController(idCliente);
            
            View_Cli_Id.setText(Integer.toString(modelCliente.getId()));
            View_Cli_Nome.setText(modelCliente.getNome());
            View_Cli_CPF.setText(modelCliente.getCpf());
            View_ComboBox_M_F.setSelectedItem(modelCliente.getSexo());
            View_ComboBox_PJ_PF.setSelectedItem(modelCliente.getClasse_cli());
            View_Cli_Tel.setText(modelCliente.getTelefone());
            View_Cli_Email.setText(modelCliente.getEmail());
            View_Cli_CNPJ.setText(modelCliente.getCnpj());
            View_Cli_RSocial.setText(modelCliente.getRazao_social());
            View_Cli_InscEstadual.setText(modelCliente.getInscricao_estadual());
            View_Cli_NFantasia.setText(modelCliente.getNome_fantasia());
            View_Con_Capital.setText("R$"+Float.toString(modelCliente.getCapital()).replace(".", ","));
            
             regraCampoClasseCli();
            
        
        }
    }//GEN-LAST:event_View_Cli_Bt_AlterarActionPerformed

    private void View_ComboBox_PJ_PFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_ComboBox_PJ_PFActionPerformed
        // TODO add your handling code here:
         regraCampoClasseCli();
    }//GEN-LAST:event_View_ComboBox_PJ_PFActionPerformed

    private void btn_voltar_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_cliActionPerformed
        // TODO add your handling code here:
        ViewInicio viewInicio = new ViewInicio();
        viewInicio.setVisible(true);
        setVisible(false);
        
        
    }//GEN-LAST:event_btn_voltar_cliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel1;
    private javax.swing.JButton View_Cli_Bt_Alterar;
    private javax.swing.JButton View_Cli_Bt_Excluir;
    private javax.swing.JButton View_Cli_Bt_Limpar;
    private javax.swing.JButton View_Cli_Bt_Salvar;
    private javax.swing.JFormattedTextField View_Cli_CNPJ;
    private javax.swing.JFormattedTextField View_Cli_CPF;
    private javax.swing.JTextField View_Cli_DataCadastro;
    private javax.swing.JTextField View_Cli_Email;
    private javax.swing.JTextField View_Cli_Id;
    private javax.swing.JTextField View_Cli_InscEstadual;
    private javax.swing.JTextField View_Cli_NFantasia;
    private javax.swing.JTextField View_Cli_Nome;
    private javax.swing.JTextField View_Cli_RSocial;
    private javax.swing.JTable View_Cli_Tabela;
    private javax.swing.JFormattedTextField View_Cli_Tel;
    private javax.swing.JComboBox<String> View_ComboBox_M_F;
    private javax.swing.JComboBox<String> View_ComboBox_PJ_PF;
    private javax.swing.JFormattedTextField View_Con_Capital;
    private javax.swing.JButton btn_voltar_cli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
