/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.ControllerEndereco;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelCliente;
import model.ModelEndereco;


/**
 *
 * @author Marilia
 */
public class ViewEndereco extends javax.swing.JFrame {
 
    ViewConta viewConta = new ViewConta();
    ModelEndereco modelEndereco = new ModelEndereco();
    ModelCliente modelCliente = new ModelCliente();
    ControllerEndereco controllerEndereco = new ControllerEndereco();
    List<ModelEndereco> listaEndereco = new ArrayList();
    String AltCadas = "Cadastrar";
    
    /**
     * Creates new form ViewEndereco1
     */
    public ViewEndereco() {
        initComponents();
        carregarListaEndereco();
        setLocationRelativeTo(null);
       
        
    }
    
    public void ViewEnderecoFecha(){
        setVisible(false);
    }
    
    /**
     * Receber o id da view cliente
     * @param idcliente 
     */
    public void enviaidcliente(int idcliente){
        View_ende_cli_id.setText(Integer.toString(idcliente));
        View_ende_cli_id.setEnabled(false);
    }
    
    /**
     * Limpa Formulario do cliente
     * 
     */
    private void limparFormulario(){
       
        View_ende_cli_id.setText("");
        View_Ender_Endereco.setText("");
        View_Ender_Numero.setText("");
        View_Ender_Bairro.setText("");
        View_Ender_Comple.setText("");
        View_Ender_Cidade.setText("");
        View_Ender_UF.setText("");
        View_Ender_CEP.setText("");
        
       
        
        AltCadas = "Cadastrar";
       
    }
    
     /**
     * Carregar Lista na tabela da view Cliente
     *  
     */
    private void carregarListaEndereco(){
        listaEndereco = controllerEndereco.getListaEnderecoController();
        DefaultTableModel modelo = (DefaultTableModel) View_End_Tabela.getModel();
        modelo.setNumRows(0);
        
        for(int i = 0; i < listaEndereco.size(); i++){
            
                modelo.addRow(new Object[]{
                listaEndereco.get(i).getId_ende(),
                listaEndereco.get(i).getEndereco(),
                listaEndereco.get(i).getNumero(),
                listaEndereco.get(i).getComplemento(),
                listaEndereco.get(i).getBairro(),
                listaEndereco.get(i).getCidade(),
                listaEndereco.get(i).getUf()

            });
            
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        View_Ender_Endereco = new javax.swing.JTextField();
        View_Ender_Numero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        View_Ender_Bairro = new javax.swing.JTextField();
        View_Ender_Comple = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        View_Ender_Cidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        View_Ender_UF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        View_Ender_CEP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        View_End_Tabela = new javax.swing.JTable();
        View_End_Bt_Salvar = new javax.swing.JButton();
        View_End_Bt_Limpar = new javax.swing.JButton();
        View_End_Bt_Alterar = new javax.swing.JButton();
        View_End_Bt_Excluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        View_ende_cli_id = new javax.swing.JTextField();
        btn_volta_ende = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setText("Endereço");

        jLabel11.setText("Numero");

        jLabel12.setText("Bairro");

        jLabel13.setText("Complemento");

        jLabel14.setText("Cidade");

        jLabel15.setText("UF");

        jLabel16.setText("CEP");

        View_End_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id_ende", "Endereço", "Número", "Complemento", "Bairro", "Cidade", "UF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(View_End_Tabela);
        if (View_End_Tabela.getColumnModel().getColumnCount() > 0) {
            View_End_Tabela.getColumnModel().getColumn(0).setMinWidth(1);
            View_End_Tabela.getColumnModel().getColumn(0).setPreferredWidth(1);
            View_End_Tabela.getColumnModel().getColumn(0).setMaxWidth(1);
        }

        View_End_Bt_Salvar.setText("Cadastrar");
        View_End_Bt_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_End_Bt_SalvarActionPerformed(evt);
            }
        });

        View_End_Bt_Limpar.setText("Limpar");
        View_End_Bt_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_End_Bt_LimparActionPerformed(evt);
            }
        });

        View_End_Bt_Alterar.setText("Alterar");
        View_End_Bt_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_End_Bt_AlterarActionPerformed(evt);
            }
        });

        View_End_Bt_Excluir.setText("Excluir");
        View_End_Bt_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_End_Bt_ExcluirActionPerformed(evt);
            }
        });

        jLabel1.setText("IdCliente");

        btn_volta_ende.setText("Volta");
        btn_volta_ende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volta_endeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(View_End_Bt_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(View_End_Bt_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(View_End_Bt_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(View_End_Bt_Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(View_Ender_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(View_Ender_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(View_Ender_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(View_ende_cli_id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(View_Ender_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(View_Ender_Comple, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(View_Ender_Cidade)
                                        .addGap(8, 8, 8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(View_Ender_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_volta_ende, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(View_Ender_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_Ender_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_Ender_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_Ender_Comple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_Ender_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_Ender_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(View_Ender_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_ende_cli_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(View_End_Bt_Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(View_End_Bt_Alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View_End_Bt_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View_End_Bt_Salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_volta_ende, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void View_End_Bt_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_End_Bt_SalvarActionPerformed
        // TODO add your handling code here:
        modelEndereco = new ModelEndereco();
        modelCliente = new ModelCliente();
       
        modelEndereco.setEndereco(View_Ender_Endereco.getText());
        modelEndereco.setNumero(View_Ender_Numero.getText());
        modelEndereco.setBairro(View_Ender_Bairro.getText());
        modelEndereco.setComplemento(View_Ender_Comple.getText());
        modelEndereco.setCidade(View_Ender_Cidade.getText());
        modelEndereco.setUf(View_Ender_UF.getText());
        modelEndereco.setCep(View_Ender_CEP.getText());
        
        
        if(AltCadas.equals("Cadastrar")){
            modelEndereco.setCliente_id_cliente(Integer.parseInt(View_ende_cli_id.getText()));
            if(controllerEndereco.salvarEnderecoController(modelEndereco)){
                //cadastrou
                    JOptionPane.showMessageDialog(this, "Cadastro Realizado com Sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    
                    String guarda = View_ende_cli_id.getText();
                    //limpar
                    limparFormulario();
                    carregarListaEndereco();
                   
                     if(!guarda.isEmpty()){

                         viewConta.enviaidcliente(modelEndereco.getCliente_id_cliente());
                         viewConta.setLocationRelativeTo(null);
                         viewConta.setVisible(true);
                         viewConta.setResizable(false);
                         setVisible(false);
                     }

                }else{
                //não cadastrou
                    JOptionPane.showMessageDialog(this, "Erro ao Cadastrar", "Erro", JOptionPane.ERROR_MESSAGE);
                }
        }else{
             int linha = View_End_Tabela.getSelectedRow();
             int idEndere = (int) View_End_Tabela.getValueAt(linha, 0);
             modelEndereco.setId_ende(idEndere);
           if(controllerEndereco.atualizarEnderecoController(modelEndereco)){
                //cadastrou
                    JOptionPane.showMessageDialog(this, "Atualização feita com Sucesso!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    //limpar
                    limparFormulario();
                    carregarListaEndereco();
                }else{
                //não cadastrou
                    JOptionPane.showMessageDialog(this, "Erro na Atualização", "Erro", JOptionPane.ERROR_MESSAGE);
                } 
        }
        
        

    }//GEN-LAST:event_View_End_Bt_SalvarActionPerformed

    private void View_End_Bt_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_End_Bt_LimparActionPerformed
        // TODO add your handling code here:
        limparFormulario();
    }//GEN-LAST:event_View_End_Bt_LimparActionPerformed

    private void View_End_Bt_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_End_Bt_AlterarActionPerformed
        // TODO add your handling code here:
           AltCadas = "Alterar";
           modelEndereco = new ModelEndereco();
        int linha = View_End_Tabela.getSelectedRow();
        if(linha < 0){
            JOptionPane.showMessageDialog(this, "Endereço não selecionado", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }else{
            int idEndere = (int) View_End_Tabela.getValueAt(linha, 0);
            modelEndereco = controllerEndereco.getEnderecoController(idEndere);
            
            View_Ender_Endereco.setText(modelEndereco.getEndereco());
            View_Ender_Numero.setText(modelEndereco.getNumero());
            View_Ender_Bairro.setText(modelEndereco.getBairro());
            View_Ender_Comple.setText(modelEndereco.getComplemento());
            View_Ender_Cidade.setText(modelEndereco.getCidade());
            View_Ender_UF.setText(modelEndereco.getUf());
            View_Ender_CEP.setText(modelEndereco.getCep());
            View_ende_cli_id.setText(Integer.toString(modelEndereco.getCliente_id_cliente()));
            
            
            

        }
    }//GEN-LAST:event_View_End_Bt_AlterarActionPerformed

    private void View_End_Bt_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_End_Bt_ExcluirActionPerformed
        // TODO add your handling code here:
        int linha = View_End_Tabela.getSelectedRow();
        if(linha < 0){
            JOptionPane.showMessageDialog(this, "Endereço não selecionado", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }else{
            int codigo = (int) View_End_Tabela.getValueAt(linha, 0);
            if(controllerEndereco.excluirEnderecoController(codigo)){
                carregarListaEndereco();
                
                JOptionPane.showMessageDialog(this, "Endereço Excluído", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(this, "Erro ao Excluir", "Erro", JOptionPane.ERROR);   
            }
            
            
        }
    }//GEN-LAST:event_View_End_Bt_ExcluirActionPerformed

    private void btn_volta_endeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volta_endeActionPerformed
        // TODO add your handling code here:
        ViewInicio v = new ViewInicio();
        v.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_volta_endeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEndereco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton View_End_Bt_Alterar;
    private javax.swing.JButton View_End_Bt_Excluir;
    private javax.swing.JButton View_End_Bt_Limpar;
    private javax.swing.JButton View_End_Bt_Salvar;
    private javax.swing.JTable View_End_Tabela;
    private javax.swing.JTextField View_Ender_Bairro;
    private javax.swing.JTextField View_Ender_CEP;
    private javax.swing.JTextField View_Ender_Cidade;
    private javax.swing.JTextField View_Ender_Comple;
    private javax.swing.JTextField View_Ender_Endereco;
    private javax.swing.JTextField View_Ender_Numero;
    private javax.swing.JTextField View_Ender_UF;
    private javax.swing.JTextField View_ende_cli_id;
    private javax.swing.JButton btn_volta_ende;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   
}
